# Generated by Django 3.2.9 on 2023-06-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_stu_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='fac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('pass1', models.TextField(max_length=50, null=True)),
                ('type', models.TextField(max_length=50, null=True)),
            ],
        ),
    ]
