# Generated by Django 3.2.9 on 2023-06-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20230605_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='fac',
            name='type',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stu',
            name='type',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
