# Generated by Django 3.2.9 on 2023-06-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20230605_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fac',
            old_name='type',
            new_name='type1',
        ),
        migrations.RenameField(
            model_name='stu',
            old_name='type',
            new_name='type1',
        ),
    ]
